[package]
name = "glitter"
version = "0.1.0"
authors = ["Kyle Lacy <kylewlacy@me.com>"]

[features]
default = ["cgmath"]

[dependencies]
bitflags = "0.3.2"
gl = "0.0.12"

[dependencies.cgmath]
version = "^0.3.1"
optional = true
